
const fldTypes = {
	"1":["dbBoolean","boolean"],
	"2":["dbByte",""],
	"3":["dbInteger","smallint"],
	"4":["dbLong","integer"],
	"5":["dbCurrency",""],
	"6":["dbSingle","float4"],
	"7":["dbDouble","float8"],
	"8":["dbDate",""],
	"9":["dbBinary",""],
	"10":["dbText","varchar"],
	"11":["dbLongBinary",""],
	"12":["dbMemo","text"],
	"15":["dbGUID",""],
	"16":["dbBigInt",""],
	"17":["dbVarBinary",""],
	"18":["dbChar",""],
	"19":["dbNumeric",""],
	"20":["dbDecimal","numeric(18,2)"],
	"21":["dbFloat",""],
	"22":["dbTime",""],
	"23":["dbTimeStamp",""],
	"80":["dbTimeStamp80","date"],
	"81":["dbTimeStamp81","time"],
	"82":["dbTimeStamp82","timestamp"],
	"101":["dbAttachment",""],
	"102":["dbComplexByte",""],
	"103":["dbComplexInteger",""],
	"104":["dbComplexLong",""],
	"105":["dbComplexSingle",""],
	"106":["dbComplexDouble",""],
	"107":["dbComplexGUID",""],
	"108":["dbComplexDecimal",""],
	"109":["dbComplexText",""],
};

module.exports = {fldTypes}; 
